/**
 * Database snapshots: a plain-SQL copy of Willow's data that can live in Git.
 *
 * - exportSnapshot(sqlDb) returns deterministic SQL (rows ordered by rowid) for
 *   every table except session revocations, plus AUTOINCREMENT counters.
 * - importSnapshot(sqlDb, sql) loads it into a database whose schema already
 *   exists (columns are named, so older snapshots load into newer schemas).
 *
 * Sessions live in a separate store and are never part of a snapshot.
 */
const EXCLUDED = new Set(['revoked_sessions', 'sqlite_sequence']);
const HEADER = '-- Willow database snapshot. Generated by `npm run db:save`; restored automatically when no database exists.';

function quote(value) {
    if (value === null || value === undefined) return 'NULL';
    if (typeof value === 'number' || typeof value === 'bigint') return String(value);
    if (value instanceof Uint8Array) return `X'${Buffer.from(value).toString('hex')}'`;
    return `'${String(value).replace(/'/g, "''")}'`;
}

function rows(sqlDb, sql) {
    const result = sqlDb.exec(sql);
    if (!result.length) return { columns: [], values: [] };
    return result[0];
}

function exportSnapshot(sqlDb) {
    const tables = rows(sqlDb, "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").values.map(row => row[0]).filter(name => !EXCLUDED.has(name));
    const lines = [HEADER, 'PRAGMA foreign_keys = OFF;', 'BEGIN TRANSACTION;'];
    let total = 0;
    for (const table of tables) {
        const ident = `"${table.replace(/"/g, '""')}"`;
        lines.push('', `-- ${table}`, `DELETE FROM ${ident};`);
        const withoutRowid = /WITHOUT ROWID/i.test(rows(sqlDb, `SELECT sql FROM sqlite_master WHERE name = ${quote(table)}`).values[0][0] || '');
        const data = rows(sqlDb, `SELECT * FROM ${ident}${withoutRowid ? '' : ' ORDER BY rowid'}`);
        const columns = data.columns.map(column => `"${column.replace(/"/g, '""')}"`).join(', ');
        data.values.forEach(values => lines.push(`INSERT INTO ${ident} (${columns}) VALUES (${values.map(quote).join(', ')});`));
        total += data.values.length;
    }
    const sequences = rows(sqlDb, "SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'sqlite_sequence'").values.length
        ? rows(sqlDb, 'SELECT name, seq FROM sqlite_sequence ORDER BY name').values.filter(([name]) => !EXCLUDED.has(name))
        : [];
    if (sequences.length) {
        lines.push('', '-- AUTOINCREMENT counters');
        sequences.forEach(([name, seq]) => {
            lines.push(`DELETE FROM sqlite_sequence WHERE name = ${quote(name)};`);
            lines.push(`INSERT INTO sqlite_sequence (name, seq) VALUES (${quote(name)}, ${quote(seq)});`);
        });
    }
    lines.push('', 'COMMIT;', 'PRAGMA foreign_keys = ON;', '');
    return { sql: lines.join('\n'), tables: tables.length, rows: total };
}

/** Loads a snapshot into an initialized database. Throws (and rolls back) on any error. */
function importSnapshot(sqlDb, sql) {
    if (typeof sql !== 'string' || !sql.startsWith(HEADER.slice(0, 30))) throw new Error('This file is not a Willow database snapshot.');
    try {
        sqlDb.exec(sql);
    } catch (error) {
        try { sqlDb.exec('ROLLBACK;'); } catch (rollback) { /* nothing open */ }
        sqlDb.exec('PRAGMA foreign_keys = ON;');
        throw new Error(`The snapshot could not be restored: ${error.message}`, { cause: error });
    }
}

module.exports = { exportSnapshot, importSnapshot, HEADER };
